site: "Journal d'un voyageur"
url: "https://journaldunvoyageur.fr"
title: "Journal d'un voyageur"
tagline: "Découvrez le monde à travers le journal d'un voyageur."
description: "Découvrez le monde à travers le journal d'un voyageur."
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  projects:
    output: true
    permalink: /project/:slug
    
include: [".well-known"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 6
paginate_path: "/page:num/"
  
